### ISSUE TITLE
Uncaught UnexpectedValueException: Unimplemented object type: 0x9

### ISSUE THREAD

**Issue by DEZwak** [readdle/app-store-receipt-verification#2]
Trying to run \Readdle\AppStoreReceiptVerification\AppStoreReceiptVerification::verifyReceipt() on a receipt I have and it dies with this error. Reading up a bit I believe this is tied to not implementing the REAL type as per the 09 here https://www.oss.com/asn1/resources/asn1-made-simple/asn1-quick-reference.html

Any chance this could get fixed/added?

**Comment by pkotets** [comment]
Hey,

Thanks for pointing this out! Unfortunately, I can only try to implement it blindly, guessing where it is and how it looks. Not the best idea, imo.

At the same time, there are two better options:
1) if you don't mind, you can share the receipt with me (I will, by all means, treat it as a confidential piece of information and won't share it anywhere) so I can implement this type using it
OR
2) you can implement it yourself and submit a PR; it's pretty easy to implement; you can see an example of the same situation here: https://github.com/readdle/app-store-receipt-verification/pull/1

Looking forward to your decision :)

**Comment by pkotets** [comment]
I'm closing the issue now; feel free to reopen it if you come to some decision.
