### ISSUE TITLE
Running on one machine, verification failed on another with the exact same receiptData

### ISSUE THREAD

**Issue by rvwoens** [readdle/app-store-receipt-verification#3]
I am able to run AppStoreReceiptVerification::verifyReceipt() on my local development machine (MacOs brew php 8.1.24) but on my production server I get a "Verification failed" exception (Linux centos 9 php 8.1.25) using the exact same $receiptData. 
What could be the difference between both envirionments? Are there openssl settings maybe?
```			
$receiptData=... 
$appleIncRootCertificate=\Readdle\AppStoreReceiptVerification\Utils::DER2PEM(
   file_get_contents('https://www.apple.com/appleca/AppleIncRootCertificate.cer')
);
$response=\Readdle\AppStoreReceiptVerification\AppStoreReceiptVerification::verifyReceipt(
   $receiptData,
   $appleIncRootCertificate
);
```

testing a bit further and I found out that $this->verifyRootCertificate($trustedAppleRootCertificate) fails: openssl_x509_verify(..) returns 0

**Comment by pkotets** [comment]
Hi there,

Thanks for the report!
I just tried to reproduce it and got the same result.
However, the result was the same when I replaced PHP with the default version for CentOS 9 (8.0.30).
Also, I've checked the mentioned version (8.1.25) of PHP using Docker image (based on Alpine Linux), and everything works well there.

So, my conclusion is that it's not a problem of the library or PHP. Something seems wrong with the OpenSSL shared library. I will investigate further; however, I'm not sure I'll be able to resolve this issue.

**Comment by rvwoens** [comment]
hi. Thanks for reproducing it. I also investigated a bit further and tried openssl via the commandline:
```
$ openssl verify -CAfile ca_certificate.pem certificate.pem
```
openssl verifies the certificate OK while the php openssl does not. Strange thing is they both use the same openssl library and the same cfg files. How is this possible i wonder.

**Comment by pkotets** [comment]
https://forums.rockylinux.org/t/php-8-0-13-openssl-verify-fails-on-rocky-9/7478

> sudo update-crypto-policies --set DEFAULT:SHA1

Running this fixes the problem; however not sure what to do with this information :)

**Comment by rvwoens** [comment]
ok, makes sense because SHA1 is old and deprecated but still used in the apple certificates.

**Comment by rvwoens** [comment]
info found: https://www.redhat.com/en/blog/how-customize-crypto-policies-rhel-82

This means moving from DEFAULT to DEFAULT:SHA1 (which is default + allow SHA1 if I read the docs correctly)
```
sudo update-crypto-policies --show
DEFAULT
sudo update-crypto-policies --set DEFAULT:SHA1
sudo update-crypto-policies --show
DEFAULT:SHA1
```

**Comment by pkotets** [comment]
Yes, and it seems to be the only way of making the library work.
Because there is a direct verification of a signature (verifyReceiptSignature), which uses openssl_verify() directly, and it fails (not 0, but -1) with an error "error:03000098:digital envelope routines::invalid digest". So, my guess is that OpenSSL library could not be used to verify SHA1 signatures unless SHA1 signatures are explicitly enabled in the OS.

UPDATE: ...or the verification will be implemented using pure PHP, but I believe this is not an option :)
