### ISSUE TITLE
AppReceiptField preorder_date

### ISSUE THREAD

**Issue by noemi-salaun** [readdle/app-store-receipt-verification#4]
As you can see in this documentation https://developer.apple.com/documentation/appstorereceipts/responsebody/receipt
A receipt can have `preorder_date` fields in case of a preorder

For now I'm using the verifyReceipt API call to get the information if the user has preordered my app
When comparing the response with your dev mode, I found that the field 32 contains the preorder_date

with your library
![image](https://github.com/readdle/app-store-receipt-verification/assets/2726492/90989c8b-3a5d-4917-939d-52bd6dc25b10)

VS

with verifyReceipt API call
![image](https://github.com/readdle/app-store-receipt-verification/assets/2726492/af5ed199-22e1-48a0-8882-c8b5b100d3e1)

**Comment by pkotets** [comment]
Hi!

Thanks a lot for this report, it's very valueable!
I've just released the new version with this change.
