### ISSUE TITLE
Typed property VisibleString::$value must be string, null used

### ISSUE THREAD

**Issue by orionstar** [readdle/app-store-receipt-verification#7]
Error I've got:

`Typed property Readdle\AppStoreReceiptVerification\ASN1\Universal\VisibleString::$value must be string, null used`

I updated today my apple app store notifications api integration including everything related, this lib too.
Now I'm getting api responses with the notification body v2 format:

The incoming webhook message's content (signedPayload) becomes garbage & brokes any futher processing after the base64decode is called on that... it looks like something like this:
```
"{"alg":"ES256","x5c":["MIIEM

KA=="]}\x1E╚øø¦\x1AYÜXÏ]\x1A[█ò\x1E\\x19HÄêò\x11Tı\x08ï\x08øø¦\x1AYÜXÏ]\x1A[█òURQ\x08Äêì\x19\fÏÿ═╠XïL═Ïì\vMîïN\x18X╠KYìN\fM\x19ÿNM┘\x19Yêï\x08Ö\x18]\x18HÄ×╚ÿØ[Ö\e\x19RY\x08ÄêÜ\x1DKÿ\\x1C\x18\Ö[Ø\e\x1EKÿ\\x1C\x08ï\x08Ö[ØÜ\ø█øY[Ø\x08ÄêöÏ[Ö\x18øÌ\x08ƒK\x08ØÖ\£┌[█êÄêîïî\x08ï\x08£┌Y█ÖY\x11\x18]\x19HÄîM╠Ä\fî══ìLìîƒD"@Æ░RÐÉÖXÚÝñÏÐó-'2x½aâ╗ÀØ░©░Æ±p¤\x15\x030<x\x14Ðâ┬¼~8ÁJØ§£\x01vòNö\x01}█\x7F&qÖÈ"
```

I've deleted the sensitive parts from the middle. The character decoding brokes at the marked spot: **KA=="]}**
then the many unicode control chars are starting to appear...
Tried to replace every text modifying function calls with the multibyte variations & tried to convert the string to other charset but didn't had any luck... :/

Maybe I should switch to the JWT based decoder from the other lib [https://github.com/readdle/app-store-server-api](https://github.com/readdle/app-store-server-api) and also replace the root cert with the newer one?

**Comment by pkotets** [comment]
Hello,

To be honest, I've missed the point. From what you say I see that you're trying to use this library to parse server-to-server notifications from App Store. Is that correct? If yes, then it's misuse of the library, it's not intended to deal with App Store notifications. For such a purpose you have to switch to `readdle/app-store-server-api` instead.

This library is only intended to parse App Store receipts (those, which are provided by App Store to an app on a device).

Would be great, if you can provide further clarification on what exactly you're doing and which part of the library's behaviour is unexpected.

**Comment by orionstar** [comment]
I'm trying to process both server-device & server-server receipts with this library, I saw there are a solution (AppStoreServerAPIReceiptExtender.php) by using the app-store-server-api too to merge the receipts into one data entity but didn't knew it's a requirement to do that until now... until now I tried to merge the separately processed receipts by myself... thanks for the heads up! closing the issue!
